version: '3.3'
services:
  python-app:
    build:
      dockerfile: ./Dockerfile.python
    depends_on:
      db:
        condition: service_started
    links:
      - "db:database"
  db:
    build:
      dockerfile: ./Dockerfile.db
    restart: always
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_ROOT_PASSWORD: 'my_root_passowrd'
      # User for connection from python to mysql
      MYSQL_USER: 'my_user'
      # Password for connection from python to mysql
      MYSQL_PASSWORD: 'my_password'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'