version: '3.3'
services:
  python-app:
    build:
      dockerfile: ./python/Dockerfile.python
    stdin_open: true 
    tty: true 
    depends_on:
      db:
        condition: service_started
    links:
      - "db:database"
  db:
    build:
      dockerfile: ./mysql-db/Dockerfile.db
    restart: always
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_ROOT_PASSWORD: 'my_root_passowrd'
      # User for connection from python to mysql
      MYSQL_USER: 'my_user'
      # Password for connection from python to mysql
      MYSQL_PASSWORD: 'my_password'